### ISSUE TITLE
How to start this django service, you seem to be missing manage.py

### ISSUE THREAD

**Issue by ritajie** [longshine/django-authlib-oauth2#1]

**Comment by longshine** [comment]
Hi,

This repo is not a fully Django project, but an app.
If you would like to try this code, please follow these steps:

1. Install package via
`pip install -e git+https://github.com/longshine/django-authlib-oauth2.git@main#egg=django-authlib-oauth2`

2. Add to `INSTALLED_APPS` in your Django project's `settings.py`
```
INSTALLED_APPS = [
   # ...
   'django_authlib_oauth2',
]
```

3. Append to `urlpatterns` in your root `urls.py`
```
urlpatterns += [
  path('oauth/', include('django_authlib_oauth2.urls')),
]
```

4. Run migrations.

That all for a simple setup.

I may add some demo project later.

**Comment by ritajie** [comment]
Yeah! I get it. Thank you~


------------------ Original ------------------
